/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.exammanagement;

import com.mysql.cj.x.protobuf.MysqlxCrud;
import java.io.BufferedInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author siddh
 */
public class InputSubjectList extends javax.swing.JFrame {

    /**
     * Creates new form InputSubjectList
     */
    public InputSubjectList() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        inputSubjectList = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        inputSubjectList.setText("Subject List");
        inputSubjectList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputSubjectListActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(inputSubjectList)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(inputSubjectList)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputSubjectListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputSubjectListActionPerformed
        // this would be reading a subject file with subjects in first column of first year
        // second column with second year and soo...on
          
        
        
    }//GEN-LAST:event_inputSubjectListActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InputSubjectList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InputSubjectList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InputSubjectList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InputSubjectList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InputSubjectList().setVisible(true);
            }
        });
    }

    public void readFile(){
        File excelFile;
        FileInputStream fileInputStream;
        BufferedInputStream buffered;  
        JFileChooser jfile=new JFileChooser("C:\\");
       int chosen=jfile.showOpenDialog(null);
       if(chosen==JFileChooser.APPROVE_OPTION){
            try {
                excelFile=jfile.getSelectedFile();
                fileInputStream=new FileInputStream(excelFile);
                buffered=new BufferedInputStream(fileInputStream);
                XSSFWorkbook wb=new XSSFWorkbook(buffered);
                XSSFSheet sheet=wb.getSheetAt(0);
//                Iterator<Cell> curItr= sheet.getRow(0).iterator();

                Iterator<Row> itr=sheet.iterator();
                while(itr.hasNext()){
                    Row row=itr.next();
                    Iterator<Cell> cellIterator=row.cellIterator();
                    while(cellIterator.hasNext()){
                        Cell cell=cellIterator.next();
                        System.out.print(cell.getStringCellValue()+"  ");
                    }
                    System.out.println("");
                }
//                for(int row=0;row<10;row++){
//                    XSSFRow xssfr=exceFSheet.getRow(row);
//                    for(int col=0;col<10;col++){
//                        XSSFCell xSSFCell=xssfr.getCell(col);
//                        System.out.println(xSSFCell);
//                    }
//                }
            } catch (FileNotFoundException ex) {
                JOptionPane.showMessageDialog(null,ex.getMessage());
                Logger.getLogger(AddDocuments.class.getName()).log(Level.SEVERE, null, ex);
            }
            catch(IOException ex){
                  JOptionPane.showMessageDialog(null,ex.getMessage());
                Logger.getLogger(AddDocuments.class.getName()).log(Level.SEVERE, null, ex);
            
            }
       }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton inputSubjectList;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
